on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-18.04
    name: Publish NuGet Packages
    steps:

      # Checkout
      - name: Checkout repository
        uses: actions/checkout@v2

      # Setup .NET Core
      - name: Setup .NET Core @ Latest
        uses: actions/setup-dotnet@v1
        with:
          source-url: https://nuget.pkg.github.com/tidyui/index.json
        env:
          NUGET_AUTH_TOKEN: ${{secrets.NugetAuthToken}}

      # Build and pack
      - name: Build solution and generate NuGet package
        run: ./pack.sh

      # Push to NuGet
      - name: Push generated package to GitHub registry
        run: dotnet nuget push **/*.nupkg --skip-duplicate